sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t brentpalmer/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true brentpalmer/docker-react npm run test 